---
version: "3"

networks:
  caddy:
    external: true

services:

  blocky:
    image: spx01/blocky
    container_name: blocky
    restart: unless-stopped
    ports:
      - 53:53/tcp
      - 53:53/udp
      # 443 # dns over https (requires proxy by caddy)
      - 853:853 # dns over tls
      # - "4000:4000/tcp" # Prometheus stats (if enabled).
    environment:
      - TZ=Pacific/Auckland
    volumes:
      - ./conf/config.yml:/app/config.yml
      - ./conf/dns.haume.nz.crt:/app/dns.haume.nz.crt
      - ./conf/dns.haume.nz.key:/app/dns.haume.nz.key
    networks:
      - caddy
